### PR TITLE
Merge pull request #3 from toast565/master

### PR DESCRIPTION
**Pull request by FrancescoPalma**
Update Pull Request

### CODE REVIEW

**Comment by toast565** [comment]
What is this pull request doing? :S

**Comment by FrancescoPalma** [comment]
Sorry for that, my bad. Just made a mistake while updating files. :sob:

**Comment by toast565** [comment]
Ah OK thought there was something I couldn't see. Yeah I got into some trouble with some conflicts yesterday as well and managed to delete a lot of the files in my local folder. But that's the point of this project right? Getting to know git so we don't make these mistakes again :)

**Comment by FrancescoPalma** [comment]
Exactly! I actually have another issue, maybe you can help me on that. 
I have locally on my computer the folder 'ToDoList' with all the files (I changed a lot of stuff, so I decided to download the .hmtl, .css, .js files and edit them locally rather than making a mess online). The app is ready, but I would like to show it to you so that you can study the code, see if there's anything to improve or change, any question etc. 
I'm trying to push the files from my local repo to the forked repo I have here (FrancescoPalma/ToDoList), but through HTTPS the authentication always fails.
Any idea on this?

**Comment by toast565** [comment]
hmm don't know what's going on there. Maybe stackoverflow can help?
http://stackoverflow.com/questions/17659206/git-push-results-in-authentication-failed
https://gist.github.com/wikimatze/9790374

**Pull request merged**
